import { Product, ApiResponse } from '../types/product.types'

// Local products data
const LOCAL_PRODUCTS: Product[] = [
  {
    _id: '1',
    name: 'HP Business Copy Paper Hi White',
    slug: 'hp-business-copy-paper-hi-white',
    description: 'A lightweight and economical paper designed primarily for high-volume copying and draft printing within a business environment. The "Hi White" finish provides good contrast for clear, easy-to-read text, making it suitable for internal memos, drafts, and everyday black-and-white copies where paper weight is less critical.',
    shortDescription: 'Lightweight and economical paper for high-volume copying and draft printing',
    sku: 'HP-BCP-70',
    price: 950,
    salePrice: 850,
    stock: 100,
    minStock: 10,
    images: [
      { url: '/images/HP Business Copy Paper blue.jpg', alt: 'HP Business Copy Paper Hi White' },
      { url: '/images/HP Business Copy Paper 2 blue.webp', alt: 'HP Business Copy Paper Hi White - Alternative view' }
    ],
    category: 'copy-paper',
    brand: 'hp',
    tags: ['copy-paper', 'business', 'hi-white', '70gsm'],
    attributes: ['70gsm', 'Hi White', 'Business Grade', 'High Volume'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: true,
    isDigital: false,
    reviews: [],
    rating: 4.8,
    reviewCount: 124,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: '2',
    name: 'HP Office Paper Hi White',
    slug: 'hp-office-paper-hi-white',
    description: 'A versatile, standard-weight paper ideal for general office use. Slightly heavier than basic copy paper, it offers better opacity and a more substantial feel for everyday printing tasks like emails, reports, faxes, and copies. The "Hi White" surface ensures crisp text and clear black-and-white graphics.',
    shortDescription: 'Versatile, standard-weight paper ideal for general office use with superior brightness',
    sku: 'HP-OP-75',
    price: 1020,
    salePrice: 920,
    stock: 80,
    minStock: 10,
    images: [
      { url: '/images/HP Office paper (green).jpg', alt: 'HP Office Paper Hi White' },
      { url: '/images/HP Office paper (green)#.png', alt: 'HP Office Paper Hi White - Alternative view' }
    ],
    category: 'office-paper',
    brand: 'hp',
    tags: ['office-paper', 'hi-white', '75gsm', 'versatile'],
    attributes: ['75gsm', 'Hi White', 'Office Grade', 'Versatile'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: true,
    isDigital: false,
    reviews: [],
    rating: 4.9,
    reviewCount: 89,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: '3',
    name: 'HP Everyday Paper Hi White',
    slug: 'hp-everyday-paper-hi-white',
    description: 'Considered a standard, reliable paper weight, this 80gsm option is perfect for everyday printing needs at home or in the office. It provides a good balance of thickness, opacity (reducing show-through on double-sided prints), and smooth performance in most printers and copiers.',
    shortDescription: 'Standard, reliable 80gsm paper perfect for everyday printing needs',
    sku: 'HP-EDP-80',
    price: 1100,
    salePrice: 990,
    stock: 90,
    minStock: 10,
    images: [
      { url: '/images/HP Everyday paper (orange).webp', alt: 'HP Everyday Paper Hi White' },
      { url: '/images/HP Everyday paper (orange) 2.jpg', alt: 'HP Everyday Paper Hi White - Alternative view' }
    ],
    category: 'everyday-paper',
    brand: 'hp',
    tags: ['everyday-paper', 'hi-white', '80gsm', 'reliable'],
    attributes: ['80gsm', 'Hi White', 'Everyday Grade', 'Reliable'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: true,
    isDigital: false,
    reviews: [],
    rating: 4.7,
    reviewCount: 156,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: '4',
    name: 'HP LaserJet Paper Hi White',
    slug: 'hp-laserjet-paper-hi-white',
    description: 'A heavier, more premium paper specifically optimized for LaserJet printers. The 90gsm weight gives documents a substantial, professional feel and increased opacity, ideal for double-sided printing, presentations, proposals, and important business documents. Its surface is engineered for excellent toner adhesion.',
    shortDescription: 'Premium 90gsm paper specifically optimized for LaserJet printers',
    sku: 'HP-LJP-90',
    price: 1200,
    salePrice: 1100,
    stock: 60,
    minStock: 10,
    images: [
      { url: '/images/HP Laserjet paper ( dark green).jpg', alt: 'HP LaserJet Paper Hi White' },
      { url: '/images/HP Laserjet paper ((dark green)).jpg', alt: 'HP LaserJet Paper Hi White - Alternative view' }
    ],
    category: 'laser-jet',
    brand: 'hp',
    tags: ['laser-jet', 'hi-white', '90gsm', 'premium'],
    attributes: ['90gsm', 'Hi White', 'LaserJet Optimized', 'Premium'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: true,
    isDigital: false,
    reviews: [],
    rating: 4.9,
    reviewCount: 203,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'c1',
    name: '2/S Coated Art Paper / Matt Paper',
    slug: 'two-side-coated-art-paper-matt',
    description: 'Premium two-side coated art paper available in gloss and matt finishes. Ideal for brochures, magazines, catalogs, and high-quality color printing with excellent ink holdout and smoothness.',
    shortDescription: 'Two-side coated art paper for premium color printing',
    sku: 'COATED-ART-2S',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: '2/S Coated Art Paper / Matt Paper' }],
    category: 'coated-paper-board',
    brand: 'various',
    tags: ['coated', 'art-paper', '2/s', 'gloss', 'matt'],
    attributes: ['Two-side coated', 'Gloss/Matt finish', 'High-quality color output'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'c2',
    name: '2/S Coated Paper & Board (Glossy/Matt)',
    slug: 'two-side-coated-paper-board',
    description: 'Versatile two-side coated paper and board in glossy and matt options for packaging, covers, postcards, and premium print applications.',
    shortDescription: 'Coated paper & board for covers and packaging',
    sku: 'COATED-BOARD-2S',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: '2/S Coated Paper & Board (Glossy/Matt)' }],
    category: 'coated-paper-board',
    brand: 'various',
    tags: ['coated', 'board', 'gloss', 'matt'],
    attributes: ['Two-side coated', 'Gloss/Matt', 'Rigid board options'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'f1',
    name: '1/S Coated Folding Box Board (White Back)',
    slug: 'fbb-white-back-1s',
    description: 'Folding Box Board with bleached white back and one-side coated top surface for high-quality printing and packaging.',
    shortDescription: 'FBB white back for premium folding cartons',
    sku: 'FBB-WB-1S',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: '1/S Coated Folding Box Board White Back' }],
    category: 'fbb-duplex-board',
    brand: 'various',
    tags: ['fbb', 'white-back', '1/s'],
    attributes: ['White back', 'One-side coated', 'High stiffness'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'u1',
    name: 'Uncoated Woodfree Offset Paper',
    slug: 'uncoated-woodfree-offset-paper',
    description: 'High-quality uncoated woodfree offset paper for books, forms, manuals, and general print applications with excellent runnability.',
    shortDescription: 'Uncoated woodfree paper for offset printing',
    sku: 'UWF-OFFSET',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: 'Uncoated Woodfree Offset Paper' }],
    category: 'uncoated-offset',
    brand: 'various',
    tags: ['uncoated', 'woodfree', 'offset'],
    attributes: ['Good opacity', 'Smooth uncoated surface', 'Reliable runnability'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 's1',
    name: 'Newsprint Paper',
    slug: 'newsprint-paper',
    description: 'Economical lightweight paper for newspapers, flyers, and inserts. Designed for high-speed web presses with good opacity and ink absorption.',
    shortDescription: 'Lightweight economical paper for newsprint applications',
    sku: 'NEWSPRINT',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: 'Newsprint Paper' }],
    category: 'specialty',
    brand: 'various',
    tags: ['newsprint', 'web-press'],
    attributes: ['Lightweight', 'Good opacity', 'Economical'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'c3',
    name: '1/S Coated Art Card',
    slug: 'one-side-coated-art-card',
    description: 'One-side coated art card with a printable high-gloss or matt face and an uncoated reverse. Excellent for postcards, covers, blister cards, and packaging.',
    shortDescription: 'One-side coated art card for premium covers and cards',
    sku: 'ART-CARD-1S',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: '1/S Coated Art Card' }],
    category: 'coated-paper-board',
    brand: 'various',
    tags: ['art-card', '1/s', 'coated'],
    attributes: ['One-side coated', 'High stiffness', 'Excellent printability'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'c4',
    name: 'Light Weight Coated Paper (LWC)',
    slug: 'light-weight-coated-paper-lwc',
    description: 'Lightweight coated paper optimized for magazines, inserts, and high-volume commercial printing where weight and postal costs matter.',
    shortDescription: 'Lightweight coated paper for magazines and inserts',
    sku: 'LWC-COATED',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: 'Light Weight Coated Paper (LWC)' }],
    category: 'coated-paper-board',
    brand: 'various',
    tags: ['lwc', 'coated', 'magazines'],
    attributes: ['Low basis weight', 'Good opacity', 'Smooth surface'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'c5',
    name: 'Both Sides Coated Art Card',
    slug: 'both-sides-coated-art-card',
    description: 'Premium both-sides coated art card offering superior surface uniformity and rigidity for high-end packaging, covers, and promotional materials.',
    shortDescription: 'Both-sides coated art card for premium packaging',
    sku: 'ART-CARD-2S',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: 'Both Sides Coated Art Card' }],
    category: 'coated-paper-board',
    brand: 'various',
    tags: ['art-card', '2/s', 'coated'],
    attributes: ['Two-side coated', 'High rigidity', 'Excellent smoothness'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'f2',
    name: '1/S Coated Folding Box Board (Manila Back)',
    slug: 'fbb-manila-back-1s',
    description: 'Folding Box Board with manila (kraft) back and coated top surface, widely used for pharmaceutical and FMCG packaging.',
    shortDescription: 'FBB manila back for versatile packaging',
    sku: 'FBB-MB-1S',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: '1/S Coated Folding Box Board Manila Back' }],
    category: 'fbb-duplex-board',
    brand: 'various',
    tags: ['fbb', 'manila-back', '1/s'],
    attributes: ['Manila back', 'One-side coated', 'Good print surface'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'f3',
    name: '1/S Coated Folding Board White Back',
    slug: 'folding-board-white-back-1s',
    description: 'Coated folding board with white back for consumer packaging requiring clean aesthetics and reliable converting performance.',
    shortDescription: 'Coated folding board white back',
    sku: 'FB-WB-1S',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: '1/S Coated Folding Board White Back' }],
    category: 'fbb-duplex-board',
    brand: 'various',
    tags: ['folding-board', 'white-back', '1/s'],
    attributes: ['White back', 'Coated top', 'Carton converting'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'f4',
    name: '1/S Coated Duplex Board (Grey Back)',
    slug: 'duplex-board-grey-back-1s',
    description: 'Cost-effective duplex board with grey back and coated top surface, suitable for packaging, boxes, and inserts.',
    shortDescription: 'Coated duplex board with grey back',
    sku: 'DUPLEX-GB-1S',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: '1/S Coated Duplex Board Grey Back' }],
    category: 'fbb-duplex-board',
    brand: 'various',
    tags: ['duplex', 'grey-back', '1/s'],
    attributes: ['Grey back', 'Coated top', 'Value packaging'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'u2',
    name: 'Woodfree Printing Paper 50gsm (Religious Publications)',
    slug: 'woodfree-printing-paper-50gsm',
    description: 'Lightweight 50gsm woodfree printing paper designed for high pagination, religious publications, and cost-effective mass printing with acceptable show-through control.',
    shortDescription: 'Lightweight 50gsm woodfree paper for religious publications',
    sku: 'UWF-50GSM',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: 'Woodfree Printing Paper 50gsm' }],
    category: 'uncoated-offset',
    brand: 'various',
    tags: ['woodfree', '50gsm', 'printing'],
    attributes: ['50gsm', 'Low weight', 'High pagination'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'u3',
    name: 'Hi Bright Offset Paper',
    slug: 'hi-bright-offset-paper',
    description: 'Uncoated offset paper with elevated brightness for crisp text and graphics, suitable for commercial print, books, and stationery.',
    shortDescription: 'High-brightness uncoated offset paper',
    sku: 'HI-BRIGHT-OFFSET',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: 'Hi Bright Offset Paper' }],
    category: 'uncoated-offset',
    brand: 'various',
    tags: ['offset', 'hi-bright', 'uncoated'],
    attributes: ['High brightness', 'Uncoated', 'Good print contrast'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 's2',
    name: 'Thermal Paper',
    slug: 'thermal-paper',
    description: 'Heat-sensitive coated paper for POS receipts, labels, and tickets, compatible with thermal printers for sharp black imaging.',
    shortDescription: 'Thermal paper for POS and ticketing',
    sku: 'THERMAL',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: 'Thermal Paper' }],
    category: 'specialty',
    brand: 'various',
    tags: ['thermal', 'pos', 'labels'],
    attributes: ['Thermal coating', 'Sharp imaging', 'POS compatible'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 's3',
    name: 'Sticker Paper',
    slug: 'sticker-paper',
    description: 'Adhesive-backed paper for labeling and stickers, available in various face stocks and adhesive types for packaging and retail needs.',
    shortDescription: 'Adhesive paper for labels and stickers',
    sku: 'STICKER',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: 'Sticker Paper' }],
    category: 'specialty',
    brand: 'various',
    tags: ['sticker', 'label', 'adhesive'],
    attributes: ['Adhesive-backed', 'Multiple face stocks', 'Packaging/Retail'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 's4',
    name: 'Pure Kraft Liner Board',
    slug: 'pure-kraft-liner-board',
    description: 'Strong, natural kraft liner board used in corrugated packaging for excellent burst and compression strength.',
    shortDescription: 'Natural kraft liner for corrugated packaging',
    sku: 'KRAFT-LINER',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: 'Pure Kraft Liner Board' }],
    category: 'specialty',
    brand: 'various',
    tags: ['kraft', 'liner', 'corrugated'],
    attributes: ['High strength', 'Natural kraft', 'Packaging'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 's5',
    name: 'Uncoated Cream Card',
    slug: 'uncoated-cream-card',
    description: 'Premium uncoated cream card stock for invitations, certificates, and upscale stationery with a natural tactile feel.',
    shortDescription: 'Premium cream card for stationery and invites',
    sku: 'CREAM-CARD',
    price: 0,
    stock: 0,
    minStock: 0,
    images: [{ url: '/images/hplogo.png', alt: 'Uncoated Cream Card' }],
    category: 'specialty',
    brand: 'various',
    tags: ['card', 'uncoated', 'cream'],
    attributes: ['Uncoated', 'Cream shade', 'Premium tactile feel'],
    variations: [],
    seo: {},
    status: 'published',
    isActive: true,
    isFeatured: false,
    isDigital: false,
    reviews: [],
    rating: 5,
    reviewCount: 0,
    viewCount: 0,
    salesCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
]

export const productService = {
  async getFeaturedProducts(limit: number = 6): Promise<ApiResponse<{ products: Product[] }>> {
    // Return local products data only - no API calls
    const featuredProducts = LOCAL_PRODUCTS.filter(product => product.isFeatured && product.isActive)
    const limitedProducts = featuredProducts.slice(0, limit)
    
    return {
      success: true,
      data: { products: limitedProducts }
    }
  },
  
  async getAllProducts(): Promise<ApiResponse<{ products: Product[] }>> {
    // Return all local products - no API calls
    const activeProducts = LOCAL_PRODUCTS.filter(product => product.isActive)
    
    return {
      success: true,
      data: { products: activeProducts }
    }
  },
}
